from reportlab.lib.pagesizes import LETTER
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
from reportlab.lib.units import inch

# --- 150 QUESTIONS DATA ---
# Structure: (Topic Code, Question, [Option A, Option B, Option C, Option D], Correct Index (0-3), Rationale)

questions_data = [
    # --- A. NATURE AND IMPORTANCE (15 Questions) ---
    ("A", "Which act is known as the 'Agriculture and Fisheries Modernization Act of 1997'?",
     ["RA 8435", "RA 9003", "RA 10068", "RA 7607"], 0,
     "RA 8435 is the AFMA Law. RA 9003 is Solid Waste Management; RA 10068 is Organic Agriculture; RA 7607 is the Magna Carta for Small Farmers."),
    ("A", "Which of the following best defines 'Agriculture' in a modern context?",
     ["Cultivation of crops only", "Raising of livestock only", "The art and science of producing crops and livestock for economic purposes", "The manufacturing of processed food"], 2,
     "Agriculture encompasses both crops and livestock, and involves science, art, and business."),
    ("A", "The 'Green Revolution' in the Philippines was primarily focused on increasing the production of:",
     ["Coconut and Abaca", "Rice and Corn", "Banana and Mango", "Root crops"], 1,
     "The Green Revolution (Masagana 99) focused on high-yielding varieties of rice and corn to ensure food security."),
    ("A", "Which government agency is primarily responsible for the promotion of agricultural development in the Philippines?",
     ["DENR", "DA", "DOST", "DAR"], 1,
     "DA (Department of Agriculture) is the primary agency. DENR focuses on environment/natural resources; DAR on land reform; DOST on science/tech."),
    ("A", "Agro-industries differ from traditional farming because they:",
     ["Use only organic methods", "Involve the processing and value-adding of agricultural products", "Are done only in urban areas", "Do not use soil"], 1,
     "Agro-industries link agriculture with manufacturing (processing), adding value to raw materials."),
    ("A", "The primary objective of 'Subsistence Farming' is:",
     ["Export to international markets", "Profit maximization", "Feeding the farmer's family", "Raw material for factories"], 2,
     "Subsistence farming focuses on self-sufficiency for the household, not commercial sale."),
    ("A", "Which of the following is considered a 'High Value Crop' (HVC) in the Philippines under RA 7900?",
     ["Rice", "Corn", "Mango", "Grass"], 2,
     "HVCs like Mango, Banana, and Coffee typically command higher prices than staples like rice and corn."),
    ("A", "The International Rice Research Institute (IRRI) is located in:",
     ["Quezon City", "Los Baños, Laguna", "Muñoz, Nueva Ecija", "Davao City"], 1,
     "IRRI is headquartered in Los Baños, Laguna. PhilRice is in Muñoz."),
    ("A", "Which sector typically contributes the largest share to the Gross Value Added (GVA) in Philippine Agriculture?",
     ["Forestry", "Livestock", "Crops", "Fisheries"], 2,
     "Crops (especially rice, corn, coconut, banana) historically make up the largest chunk of Agri GVA."),
    ("A", "Which milestone law aims to promote Organic Agriculture in the Philippines?",
     ["RA 8435", "RA 10068", "RA 9160", "RA 7160"], 1,
     "RA 10068 is the Organic Agriculture Act of 2010."),
    ("A", "What does 'Food Security' primarily imply?",
     ["Everyone has expensive food", "Food is available, accessible, and utilized by all people at all times", "Only the rich have food", "Food is imported"], 1,
     "Food security is defined by availability, accessibility, utilization, and stability."),
    ("A", "Agronomy differs from Horticulture in that Agronomy deals primarily with:",
     ["Garden crops", "Field crops grown extensively", "Fruits and vegetables", "Ornamentals"], 1,
     "Agronomy deals with extensive field crops (grains, forages). Horticulture deals with intensive garden crops (fruits, veg, ornamentals)."),
    ("A", "Which is NOT a branch of Crop Science?",
     ["Agronomy", "Horticulture", "Animal Science", "Plant Breeding"], 2,
     "Animal Science deals with livestock. Agronomy, Horticulture, and Breeding are sub-disciplines of Crop Science."),
    ("A", "The 'Father of the Green Revolution' is:",
     ["Gregor Mendel", "Norman Borlaug", "Charles Darwin", "Louis Pasteur"], 1,
     "Norman Borlaug developed high-yielding wheat varieties. Mendel is Father of Genetics."),
    ("A", "The specialized UN agency for hunger and agriculture is:",
     ["WHO", "FAO", "UNESCO", "ILO"], 1,
     "FAO (Food and Agriculture Organization)."),

    # --- B. CLASSIFICATION (15 Questions) ---
    ("B", "Which is the correct scientific name of Corn?",
     ["Zea Mays", "Zea mays", "zea mays", "Zea Mays L."], 1,
     "Genus capitalized, species lowercase. (Option D has 'Mays' capitalized which is wrong)."),
    ("B", "Rice belongs to the family:",
     ["Fabaceae", "Poaceae", "Solanaceae", "Cucurbitaceae"], 1,
     "Poaceae (formerly Gramineae) is the grass family."),
    ("B", "Mungbean (*Vigna radiata*) is a member of which family?",
     ["Poaceae", "Fabaceae", "Leguminosae", "Both B and C"], 3,
     "Fabaceae is the current name; Leguminosae is the old name. Both are accepted."),
    ("B", "Which of the following is a 'Biennial' crop?",
     ["Rice", "Radish (for seed)", "Mango", "Corn"], 1,
     "Radish, Onion, and Cabbage are biennials (vegetative in year 1, reproductive in year 2) usually grown as annuals for veg."),
    ("B", "Crops grown primarily to cover the soil and prevent erosion are called:",
     ["Catch crops", "Cover crops", "Trap crops", "Nurse crops"], 1,
     "Cover crops protect soil. Catch crops utilize short growing windows. Trap crops attract pests."),
    ("B", "Which crop is classified as a 'Monocot'?",
     ["Bean", "Tomato", "Coconut", "Peanut"], 2,
     "Coconut (palm) is a monocot. Beans, Tomatoes, Peanuts are dicots."),
    ("B", "A 'Companion Crop' is:",
     ["Planted to attract insects away from main crop", "Planted with another crop to benefit one or both", "Planted after the main crop fails", "Planted to kill weeds"], 1,
     "Companion planting provides mutual benefits (e.g., nitrogen fixing, structural support)."),
    ("B", "Sweet potato (*Ipomoea batatas*) belongs to the family:",
     ["Solanaceae", "Convolvulaceae", "Brassicaceae", "Liliaceae"], 1,
     "Convolvulaceae (Morning Glory family). Solanaceae is Potato/Tomato."),
    ("B", "The scientific name of Mango is:",
     ["Mangifera indica", "Musa sapientum", "Carica papaya", "Psidium guajava"], 0,
     "Mangifera indica. Musa is Banana, Carica is Papaya, Psidium is Guava."),
    ("B", "Which of the following is an example of a 'Fiber Crop'?",
     ["Abaca", "Cotton", "Ramie", "All of the above"], 3,
     "Abaca (Manila hemp), Cotton, and Ramie are all grown for their fibers."),
    ("B", "Classification based on 'Life Cycle' includes:",
     ["Cereals, Legumes, Root crops", "Annuals, Biennials, Perennials", "Sexual, Asexual", "Food, Non-food"], 1,
     "Life cycle refers to the duration from seed to senescence (Annual, Biennial, Perennial)."),
    ("B", "Which crop is a 'C4 plant' (efficient in high light/temp)?",
     ["Rice", "Wheat", "Sugarcane", "Potato"], 2,
     "Sugarcane, Corn, and Sorghum are C4. Rice, Wheat, Potato are C3."),
    ("B", "Which of the following is a 'Solanaceous' crop?",
     ["Cabbage", "Eggplant", "Squash", "Okra"], 1,
     "Eggplant, Tomato, Pepper, Potato are Solanaceae."),
    ("B", "Scientific name of Coconut:",
     ["Cocos nucifera", "Elaeis guineensis", "Areca catechu", "Nypa fruticans"], 0,
     "Cocos nucifera. Elaeis is Oil Palm."),
    ("B", "Rubber (*Hevea brasiliensis*) is primarily classified as a:",
     ["Latex/Industrial crop", "Cereal crop", "Pulse crop", "Beverage crop"], 0,
     "Rubber produces latex for industry."),

    # --- C. ANATOMY (15 Questions) ---
    ("C", "Which plant tissue is responsible for transporting water from roots to leaves?",
     ["Phloem", "Xylem", "Cambium", "Epidermis"], 1,
     "Xylem transports water/minerals up. Phloem transports food (sugar) down/around."),
    ("C", "The pores on leaves that facilitate gas exchange are called:",
     ["Lenticels", "Stomata", "Hydathodes", "Cuticles"], 1,
     "Stomata (guard cells) control gas exchange (CO2 in, O2/H2O out)."),
    ("C", "Photosynthesis primarily takes place in which organelle?",
     ["Mitochondria", "Chloroplast", "Nucleus", "Ribosome"], 1,
     "Chloroplasts contain chlorophyll for photosynthesis."),
    ("C", "The 'edible part' of an Onion is a modified:",
     ["Root", "Stem", "Leaf (base)", "Flower"], 2,
     "Onion bulbs are specialized underground leaves (scales)."),
    ("C", "Nitrogen fixation in legumes occurs in nodules formed on the:",
     ["Leaves", "Stems", "Roots", "Flowers"], 2,
     "Rhizobium bacteria form nodules on the roots."),
    ("C", "Which tissue is responsible for secondary growth (thickening) in dicots?",
     ["Apical Meristem", "Vascular Cambium", "Intercalary Meristem", "Parenchyma"], 1,
     "Vascular cambium produces secondary xylem and phloem, increasing girth."),
    ("C", "The male reproductive part of a flower is the:",
     ["Pistil", "Stamen", "Sepal", "Petal"], 1,
     "Stamen (Anther + Filament). Pistil is female."),
    ("C", "A 'Perfect Flower' must have:",
     ["Sepals and Petals", "Stamen and Pistil", "Anthers only", "Stigma only"], 1,
     "Perfect (Hermaphrodite) flowers have both male (stamen) and female (pistil) parts."),
    ("C", "Which part of the seed serves as the food storage in monocots like corn?",
     ["Cotyledon", "Endosperm", "Radicle", "Testa"], 1,
     "In monocots (corn), the bulky food storage is the Endosperm."),
    ("C", "Roots that arise from stems or leaves (non-root tissue) are called:",
     ["Tap roots", "Adventitious roots", "Lateral roots", "Hair roots"], 1,
     "Adventitious roots arise from non-root parts (e.g., brace roots in corn)."),
    ("C", "The waxy layer on the leaf surface that reduces water loss is:",
     ["Cuticle", "Epidermis", "Mesophyll", "Trichome"], 0,
     "Cuticle is the waxy barrier."),
    ("C", "In a grafted plant, the bottom part with roots is called the:",
     ["Scion", "Rootstock", "Budstick", "Cambium"], 1,
     "Rootstock provides the root system; Scion provides the shoot/fruit."),
    ("C", "Which cell type is 'dead' at maturity and provides structural support?",
     ["Parenchyma", "Collenchyma", "Sclerenchyma", "Meristem"], 2,
     "Sclerenchyma (fibers/sclereids) have thick lignified walls and are dead at maturity."),
    ("C", "The arrangement of leaves on a stem is called:",
     ["Venation", "Phyllotaxy", "Inflorescence", "Morphology"], 1,
     "Phyllotaxy (Alternate, Opposite, Whorled)."),
    ("C", "The transformation of a flower into a fruit usually requires:",
     ["Pollination and Fertilization", "Germination", "Transpiration", "Photosynthesis"], 0,
     "Pollination leads to fertilization, which triggers fruit set."),

    # --- D. GROWTH AND DEVELOPMENT (15 Questions) ---
    ("D", "The phase of growth characterized by rapid increase in size and vegetative parts is:",
     ["Lag Phase", "Log (Exponential) Phase", "Senescence Phase", "Stationary Phase"], 1,
     "Log phase is the period of maximum growth rate."),
    ("D", "The type of germination where the cotyledons remain below ground (e.g., Corn) is:",
     ["Epigeal", "Hypogeal", "Viviparous", "Dormant"], 1,
     "Hypogeal = below earth. Epigeal = cotyledons emerge (e.g., Beans)."),
    ("D", "The plant hormone responsible for fruit ripening is:",
     ["Auxin", "Cytokinin", "Gibberellic Acid", "Ethylene"], 3,
     "Ethylene is the ripening gas."),
    ("D", "Which process converts light energy into chemical energy (sugar)?",
     ["Respiration", "Photosynthesis", "Transpiration", "Absorption"], 1,
     "Photosynthesis: CO2 + H2O + Light -> Sugar + O2."),
    ("D", "The loss of water vapor from plant leaves is called:",
     ["Evaporation", "Transpiration", "Guttation", "Precipitation"], 1,
     "Transpiration occurs through stomata. Guttation is liquid water loss."),
    ("D", "Which hormone is known as the 'Stress Hormone' (closes stomata during drought)?",
     ["Auxin", "ABA (Abscisic Acid)", "Gibberellin", "Cytokinin"], 1,
     "ABA signals stomatal closure to conserve water."),
    ("D", "Apical dominance (suppression of side branches) is primarily controlled by:",
     ["Auxin", "Cytokinin", "Ethylene", "ABA"], 0,
     "Auxin produced in the shoot tip inhibits lateral bud growth."),
    ("D", "The breakdown of glucose to release energy (ATP) is:",
     ["Photosynthesis", "Respiration", "Translocation", "Assimilation"], 1,
     "Respiration consumes sugar/oxygen to produce energy."),
    ("D", "Bending of plants towards light is called:",
     ["Geotropism", "Phototropism", "Thigmotropism", "Hydrotropism"], 1,
     "Phototropism (positive) is movement towards light."),
    ("D", "The transition from vegetative to reproductive stage is often triggered by:",
     ["Photoperiod (Day length)", "Soil pH", "Wind speed", "Seed size"], 0,
     "Photoperiodism controls flowering in many crops (Short-day vs Long-day)."),
    ("D", "Vernalization is the promotion of flowering by exposure to:",
     ["High temperature", "Low temperature (Cold)", "High light", "Darkness"], 1,
     "Vernalization (cold treatment) is required by some temperate crops to flower."),
    ("D", "Senescence refers to:",
     ["Seed germination", "Active growth", "Aging and eventual death of tissues", "Fruit setting"], 2,
     "Senescence is the terminal phase of aging."),
    ("D", "Which hormone stimulates stem elongation and seed germination (breaking dormancy)?",
     ["Auxin", "Gibberellin (GA)", "Ethylene", "ABA"], 1,
     "Gibberellins promote elongation (bolting) and activate enzymes for germination."),
    ("D", "The 'Source-Sink' relationship refers to the movement of:",
     ["Water", "Photosynthates (Sugars)", "Soil", "Pollen"], 1,
     "Sugars move from Source (Leaf) to Sink (Fruit/Root)."),
    ("D", "A plant that flowers when nights are longer than a critical length is a:",
     ["Long-day plant", "Short-day plant", "Day-neutral plant", "C4 plant"], 1,
     "Short-day plants need long nights (e.g., Rice, Chrysanthemum)."),

    # --- E. FACTORS AFFECTING PRODUCTION (25 Questions) ---
    ("E", "The three 'Cardinal Points' of temperature for crops are:",
     ["Low, Medium, High", "Minimum, Optimum, Maximum", "Cold, Warm, Hot", "Start, Middle, End"], 1,
     "Min (growth starts), Opt (best growth), Max (growth stops/death)."),
    ("E", "Etiolation (pale, spindly growth) is caused by lack of:",
     ["Water", "Light", "Nitrogen", "Oxygen"], 1,
     "Plants grow tall and pale seeking light."),
    ("E", "Which soil texture is generally considered 'best' for most crops due to balanced drainage and retention?",
     ["Sand", "Clay", "Silt", "Loam"], 3,
     "Loam provides the ideal balance of aeration and water holding capacity."),
    ("E", "Soil pH measures:",
     ["Nutrient content", "Soil acidity or alkalinity", "Soil moisture", "Soil texture"], 1,
     "pH is the negative log of H+ concentration."),
    ("E", "Chlorosis (yellowing) of lower/older leaves usually indicates deficiency of:",
     ["Nitrogen", "Iron", "Calcium", "Boron"], 0,
     "N is mobile, so it moves to new leaves, leaving old ones yellow."),
    ("E", "Blossom End Rot in tomatoes is a physiological disorder caused by deficiency of:",
     ["Nitrogen", "Calcium", "Potassium", "Phosphorus"], 1,
     "Calcium is immobile; deficiency affects expanding fruits."),
    ("E", "Which climate type (Corona classification) has two pronounced seasons: dry (Nov-Apr) and wet (May-Oct)?",
     ["Type I", "Type II", "Type III", "Type IV"], 0,
     "Type I (e.g., Ilocos, parts of Luzon). Type II is no dry season."),
    ("E", "The capacity of soil to hold positively charged nutrients is called:",
     ["pH", "CEC (Cation Exchange Capacity)", "EC (Electrical Conductivity)", "Bulk Density"], 1,
     "CEC indicates soil fertility potential."),
    ("E", "Waterlogging harms most crops primarily because it leads to:",
     ["Lack of Oxygen in the root zone", "Too much salt", "Too much light", "Cold soil"], 0,
     "Roots need oxygen for respiration; water displaces air."),
    ("E", "Which element is the central component of the Chlorophyll molecule?",
     ["Iron", "Magnesium", "Zinc", "Copper"], 1,
     "Magnesium (Mg) is the core of chlorophyll."),
    ("E", "Which factor is 'Biotic'?",
     ["Temperature", "Soil pH", "Insect Pests", "Rainfall"], 2,
     "Biotic = living factors (pests, diseases, weeds). Abiotic = non-living."),
    ("E", "The process where leaves curl or roll to reduce surface area during drought is:",
     ["Epinasty", "Leaf Rolling", "Abscission", "Guttation"], 1,
     "Leaf rolling minimizes water loss."),
    ("E", "Lodging in rice (falling over) is often exacerbated by excess:",
     ["Phosphorus", "Potassium", "Nitrogen", "Magnesium"], 2,
     "Excess N causes rapid, weak stem growth, leading to lodging."),
    ("E", "Photoperiodism is the response of plants to:",
     ["Light intensity", "Duration of light and dark", "Light quality (color)", "Direction of light"], 1,
     "Duration (Day length) triggers flowering."),
    ("E", "Plants that can tolerate high salinity are called:",
     ["Xerophytes", "Halophytes", "Hydrophytes", "Mesophytes"], 1,
     "Halo = Salt. Xero = Dry. Hydro = Water."),
    ("E", "Effective Rainfall refers to:",
     ["Total rainfall", "Rainfall stored in the root zone available for the plant", "Rainfall that runs off", "Rainfall that evaporates"], 1,
     "Only the water available to roots is 'effective'."),
    ("E", "Temperature Inversion (warm air over cold air) can cause which problem in orchards?",
     ["Frost damage", "Heat stroke", "Wind burn", "Flooding"], 0,
     "It traps cold air near the ground, causing frost."),
    ("E", "Relative Humidity (RH) affects crop production primarily by influencing:",
     ["Photosynthesis", "Transpiration and Disease incidence", "Germination", "Flowering"], 1,
     "High RH reduces transpiration but favors fungal diseases."),
    ("E", "Which macronutrient is most essential for root development and energy transfer (ATP)?",
     ["N", "P (Phosphorus)", "K", "S"], 1,
     "Phosphorus is key for roots and ATP."),
    ("E", "The 'Permanent Wilting Point' is:",
     ["When plants wilt during the day but recover at night", "When plants wilt and cannot recover even if watered", "When soil is fully dry", "When stomata close"], 1,
     "PWP is the soil moisture level where roots can no longer extract water."),
    ("E", "Allelopathy is:",
     ["Mutual benefit between crops", "Harmful effect of one plant on another via chemical release", "Competition for light", "Disease transmission"], 1,
     "Chemical warfare between plants (e.g., weeds suppressing crops)."),
    ("E", "Which gas is the major contributor to the Greenhouse Effect?",
     ["Oxygen", "Nitrogen", "Carbon Dioxide", "Argon"], 2,
     "CO2 (and Methane) traps heat."),
    ("E", "El Niño phenomenon typically results in:",
     ["More typhoons", "Drought / Low rainfall", "Cooler temperatures", "Flooding"], 1,
     "El Niño causes drought in the Philippines. La Niña causes rain."),
    ("E", "Vernalization is a requirement for some plants to flower, dependent on:",
     ["High Temp", "Low Temp", "High Light", "Low Light"], 1,
     "Cold exposure."),
    ("E", "Windbreaks are planted primarily to:",
     ["Produce timber", "Reduce mechanical damage and evaporation from wind", "Look good", "Attract birds"], 1,
     "Windbreaks protect crops from physical damage and desiccation."),

    # --- F. CROP IMPROVEMENT (25 Questions) ---
    ("F", "The removal of anthers from a flower before pollen acts is called:",
     ["Pollination", "Emasculation", "Fertilization", "Inoculation"], 1,
     "Emasculation prevents self-pollination in hybridization."),
    ("F", "Heterosis or Hybrid Vigor refers to:",
     ["Offspring being inferior to parents", "Offspring being superior to the average of parents", "Offspring being identical to parents", "Offspring being sterile"], 1,
     "F1 hybrids often outperform parents."),
    ("F", "A 'Pure Line' is a progeny of a:",
     ["Single self-pollinated homozygous plant", "Cross between two varieties", "Mass selection", "Clone"], 0,
     "Pure lines are genetically uniform and homozygous."),
    ("F", "Bt Corn is genetically modified to resist:",
     ["Herbicides", "Corn Borer", "Drought", "Virus"], 1,
     "Bt (Bacillus thuringiensis) toxin kills the corn borer larvae."),
    ("F", "The simplest method of breeding in self-pollinated crops is:",
     ["Mass Selection", "Hybridization", "Mutation breeding", "Polyploidy"], 0,
     "Mass selection involves choosing best plants and mixing seeds."),
    ("F", "Progeny testing is used to determine the:",
     ["Phenotype of the parent", "Genotype/Breeding value of the parent", "Yield only", "Market price"], 1,
     "You judge a parent by how good its offspring are."),
    ("F", "Which seed class is produced directly by the plant breeder?",
     ["Certified Seed", "Registered Seed", "Foundation Seed", "Breeder Seed"], 3,
     "Breeder -> Foundation -> Registered -> Certified."),
    ("F", "The color of the tag for Certified Seeds is:",
     ["White", "Red", "Green", "Blue"], 3,
     "Breeder(White), Foundation(Red), Registered(Green), Certified(Blue)."),
    ("F", "Vegetative propagation (Cloning) ensures:",
     ["Genetic variation", "True-to-type offspring", "Faster growth", "Disease resistance"], 1,
     "Clones are genetically identical to the parent."),
    ("F", "Introduction of a crop species to a new area is called:",
     ["Acclimatization", "Plant Introduction", "Domestication", "Selection"], 1,
     "Introduction is the first step in improvement."),
    ("F", "Golden Rice is engineered to produce:",
     ["Protein", "Beta-carotene (Vitamin A precursor)", "Iron", "Zinc"], 1,
     "To address Vitamin A deficiency."),
    ("F", "Inbreeding depression is the loss of vigor due to:",
     ["Cross pollination", "Repeated self-pollination in cross-pollinated crops", "Too much fertilizer", "Hybridization"], 1,
     "Selfing cross-pollinated crops (like corn) exposes deleterious recessives."),
    ("F", "Which represents a 'Clone'?",
     ["Seedling of mango", "Grafted mango", "Hybrid corn", "Rice plant"], 1,
     "Grafted plants are vegetative clones of the scion."),
    ("F", "Tissue culture relies on the concept of 'Totipotency', which is:",
     ["Ability of a cell to die", "Ability of a single cell to regenerate into a whole plant", "Resistance to virus", "Rapid growth"], 1,
     "Every plant cell has the genetic info to make a whole plant."),
    ("F", "Polyploidy involves:",
     ["Mutation of one gene", "Change in chromosome number (multiples)", "Grafting", "Fertilizer application"], 1,
     "Multiples of the haploid set (e.g., Triploid, Tetraploid)."),
    ("F", "Seed viability can be tested rapidly using:",
     ["Ragdoll method", "Tetrazolium test", "Floatation", "Field planting"], 1,
     "Tetrazolium stains living embryos red. Ragdoll measures germination (slower)."),
    ("F", "Recalcitrant seeds are seeds that:",
     ["Can be stored dry for long periods", "Die when dried or chilled (cannot be stored long)", "Have hard coats", "Are dormant"], 1,
     "e.g., Mango, Rubber, Cacao. Orthodox seeds (Rice/Corn) can be dried."),
    ("F", "The 'Center of Origin' of Rice is believed to be:",
     ["Mexico", "Southeast Asia / India", "Africa", "Europe"], 1,
     "SE Asia is the primary center."),
    ("F", "Which breeding method is used to transfer a specific gene (e.g., disease resistance) into a high yielding variety?",
     ["Mass Selection", "Backcross Breeding", "Bulk Method", "Pedigree Method"], 1,
     "Backcrossing repeatedly crosses progeny back to the 'Recurrent Parent'."),
    ("F", "Male Sterility is useful in:",
     ["Hybrid seed production", "Pure line selection", "Cloning", "Fertilizer trials"], 1,
     "It eliminates the need for emasculation."),
    ("F", "Orthodox seeds are:",
     ["Seeds that die when dried", "Seeds that can be dried to low moisture and stored cold", "Seeds that germinate immediately", "Sterile seeds"], 1,
     "Most grains and veggies are Orthodox."),
    ("F", "A 'Landrace' is:",
     ["A modern hybrid", "A primitive local variety adapted to specific local conditions", "A GMO", "A weed"], 1,
     "Landraces are traditional varieties."),
    ("F", "Gene banking is a form of:",
     ["In-situ conservation", "Ex-situ conservation", "Commercial farming", "Organic farming"], 1,
     "Conserving germplasm outside its natural habitat (in freezers/banks)."),
    ("F", "Grafting succeeds only if there is contact between the:",
     ["Bark", "Xylem", "Cambium layers", "Pith"], 2,
     "Cambial contact is essential for union formation."),
    ("F", "Which is a 'Vegetative' planting material?",
     ["Seed", "Corm", "Grain", "Kernel"], 1,
     "Corms (e.g., Banana/Gabi) are vegetative. Seeds are sexual."),

    # --- G. SUSTAINABLE CROP PRODUCTION (15 Questions) ---
    ("G", "Sustainable Agriculture aims to:",
     ["Maximize short-term profit", "Degrade soil", "Meet current needs without compromising future generations", "Use only chemicals"], 2,
     "Sustainability balances Economic, Environmental, and Social goals."),
    ("G", "SALT stands for:",
     ["Saline Agriculture Land Technology", "Sloping Agricultural Land Technology", "Sustainable Agro Land Tillage", "Soil And Land Tillage"], 1,
     "SALT is a contour farming system for uplands."),
    ("G", "IPM (Integrated Pest Management) prioritizes:",
     ["Chemical control first", "Biological and Cultural controls", "Total eradication of pests", "No action"], 1,
     "Chemicals are the last resort."),
    ("G", "Green Manuring involves:",
     ["Painting plants green", "Plowing under fresh leguminous vegetation to improve soil N", "Using animal manure", "Burning residues"], 1,
     "Legumes fix N and add organic matter."),
    ("G", "Crop Rotation prevents:",
     ["Soil erosion", "Pest and disease buildup", "Photosynthesis", "Flowering"], 1,
     "Breaking the life cycle of pest/diseases specific to one crop."),
    ("G", "Which is a component of GAP (Good Agricultural Practices)?",
     ["Food Safety", "Environmental Protection", "Worker Welfare", "All of the above"], 3,
     "GAP covers safety, environment, and quality."),
    ("G", "Mulching helps in:",
     ["Increasing evaporation", "Conserving soil moisture and suppressing weeds", "Increasing pests", "Cooling the air"], 1,
     "Mulch acts as a barrier."),
    ("G", "Organic farming prohibits:",
     ["Compost", "Synthetic fertilizers and pesticides", "Crop rotation", "Mechanical tillage"], 1,
     "Synthetics are banned."),
    ("G", "Intercropping refers to:",
     ["Growing one crop after another", "Growing two or more crops simultaneously on the same land", "Growing crops on slopes", "Growing crops in water"], 1,
     "Simultaneous cropping."),
    ("G", "The 'Economic Threshold Level' (ETL) is the point where:",
     ["Pest population is zero", "Control measures should be applied to prevent economic loss", "Damage is already severe", "Harvest is done"], 1,
     "Action is taken at ETL to prevent reaching Economic Injury Level (EIL)."),
    ("G", "Vermicomposting uses:",
     ["Ants", "Earthworms", "Beetles", "Flies"], 1,
     "Worms (e.g., African Night Crawler) decompose waste."),
    ("G", "Which is a 'Cultural Control' for pests?",
     ["Spraying insecticides", "Releasing predators", "Sanitation / Removal of infested plants", "Using GMOs"], 2,
     "Cultural controls manipulate the environment (sanitation, timing, spacing)."),
    ("G", "Alley Cropping involves:",
     ["Growing crops in alleys between hedgerows of trees/shrubs", "Growing crops in city alleys", "Monocropping", "Hydroponics"], 1,
     "Leguminous hedgerows provide mulch and N."),
    ("G", "Biofertilizers contain:",
     ["Synthetic NPK", "Living microorganisms (e.g., Rhizobium, Mycorrhiza)", "Organic matter only", "Hormones"], 1,
     "They contain live microbes that help nutrient availability."),
    ("G", "Conservation Tillage leaves at least how much residue coverage?",
     ["0%", "10%", "30%", "100%"], 2,
     "30% is the standard threshold for conservation tillage."),

    # --- H. CROP PRODUCTION PRACTICES (25 Questions) ---
    ("H", "Primary tillage (Plowing) is done to:",
     ["Level the field", "Pulverize soil clods", "Cut and invert the soil / bury weeds", "Plant seeds"], 2,
     "Plowing is deep cutting/inversion. Harrowing (secondary) levels/pulverizes."),
    ("H", "Seeding Rate Calculation: If desired pop is 50,000 and germ is 80%, how many seeds are needed?",
     ["40,000", "50,000", "62,500", "100,000"], 2,
     "50,000 / 0.80 = 62,500."),
    ("H", "Transplanting is commonly done for:",
     ["Corn", "Soybean", "Rice (Lowland)", "Mungbean"], 2,
     "Lowland rice is often transplanted. Corn/Legumes are direct seeded."),
    ("H", "Which is a maturity index for harvesting Mango?",
     ["Cracks on skin", "Formation of abscission layer", "Sinkers (sinking in 1% salt solution)", "Purple color"], 2,
     "Mature mangoes sink; immatures float."),
    ("H", "Calculation: 1 hectare, spacing 50cm x 50cm. Population?",
     ["20,000", "40,000", "10,000", "100,000"], 1,
     "10,000 / (0.5 * 0.5) = 10,000 / 0.25 = 40,000."),
    ("H", "Pruning is essential in Coffee to:",
     ["Kill the tree", "Rejuvenate and regulate bearing wood", "Increase shade", "Decrease roots"], 1,
     "Removal of old/unproductive wood stimulates new bearing wood."),
    ("H", "Trellising is required for:",
     ["Corn", "Pole Sitaw / Ampalaya", "Peanut", "Rice"], 1,
     "Vining crops need support."),
    ("H", "The 'Critical Period' for weed competition is usually:",
     ["At harvest", "First 1/3 to 1/2 of the crop life cycle", "Late season", "During storage"], 1,
     "Early weed control is crucial."),
    ("H", "Which irrigation method is most water-efficient?",
     ["Flood irrigation", "Furrow irrigation", "Drip irrigation", "Sprinkler"], 2,
     "Drip delivers water directly to roots, minimizing evaporation."),
    ("H", "Hilling-up is done in corn to:",
     ["Cover weeds and support the base (prevent lodging)", "Expose roots", "Remove fertilizer", "Harvest"], 1,
     "Adds soil to base for support and weed control."),
    ("H", "Hardening of seedlings involves:",
     ["Giving more water", "Reducing water and exposing to sunlight", "Applying fertilizer", "Keeping in dark"], 1,
     "Prepares seedling for field stress."),
    ("H", "Ratooning is a practice in:",
     ["Corn", "Sugarcane / Pineapple", "Coconut", "Mango"], 1,
     "Regrowing a second crop from the stubble/suckers."),
    ("H", "Post-harvest handling: 'Curing' is done for Onions to:",
     ["Cook them", "Dry the neck and outer scales to prevent rot", "Make them sweeter", "Remove soil"], 1,
     "Curing seals the neck."),
    ("H", "Calculation: How many hills in 1 ha at 1m x 1m spacing?",
     ["1,000", "5,000", "10,000", "20,000"], 2,
     "10,000 / 1 = 10,000."),
    ("H", "The best time to harvest most leafy vegetables is:",
     ["High noon", "Late afternoon", "Early morning", "Midnight"], 2,
     "Turgidity is highest, and temp is cool."),
    ("H", "Which is a 'climacteric' fruit (ripens after harvest)?",
     ["Pineapple", "Banana", "Grape", "Citrus"], 1,
     "Banana, Mango, Tomato ripen after picking. Non-climacteric (Pineapple, Citrus) do not."),
    ("H", "Controlled Atmosphere Storage (CAS) works by:",
     ["Increasing Oxygen", "Lowering Oxygen and increasing CO2", "Freezing", "Heating"], 1,
     "Slowing respiration by limiting O2."),
    ("H", "Seed coating (pelleting) is done to:",
     ["Make seeds look pretty", "Increase size of small seeds for easier planting", "Kill the seed", "Remove dormancy"], 1,
     "Small seeds (lettuce) are pelleted for precision planting."),
    ("H", "Desuckering is a practice in:",
     ["Rice", "Banana / Tobacco", "Corn", "Coconut"], 1,
     "Removing unwanted suckers to direct energy to main crop."),
    ("H", "Hydroponics is growing plants in:",
     ["Soil", "Nutrient solution (water)", "Sand", "Air"], 1,
     "Soilless culture."),
    ("H", "Which tool is used for measuring total soluble solids (Brix/Sweetness)?",
     ["pH meter", "Refractometer", "Thermometer", "Barometer"], 1,
     "Refractometer measures sugar content."),
    ("H", "Calculation: If 100-seed weight is 20g, how many seeds in 1 kg?",
     ["5,000", "50,000", "20,000", "10,000"], 1,
     "1 kg = 1000g. (1000 / 20) * 100 = 50 * 100 = 5,000. Wait. 20g=100seeds. 1g=5seeds. 1000g=5000seeds. Correct."),
    ("H", "Thinning is the process of:",
     ["Adding more plants", "Removing excess seedlings to reduce competition", "Adding fertilizer", "Watering"], 1,
     "Ensures proper spacing."),
    ("H", "Damping-off is a common disease in:",
     ["Mature trees", "Seedlings", "Fruits", "Seeds in storage"], 1,
     "Fungal disease killing young seedlings."),
    ("H", "Zero tillage is a form of:",
     ["Clean culture", "Conservation agriculture", "Conventional farming", "Organic farming"], 1,
     "Planting without plowing."),

    # --- I. SITE SELECTION (13 Questions to reach ~150) ---
    ("I", "Topography refers to:",
     ["Soil color", "Slope and elevation of the land", "Rainfall pattern", "Wind direction"], 1,
     "Physical lay of the land."),
    ("I", "For lowland rice, the preferred topography is:",
     ["Steep slope", "Level / Flat", "Rolling", "Hilly"], 1,
     "Flat land is needed for water retention."),
    ("I", "Which soil type is generally NOT recommended for most crops due to poor drainage?",
     ["Sandy loam", "Heavy Clay (waterlogged)", "Silt loam", "Volcanic soil"], 1,
     "Heavy clay causes waterlogging and root rot."),
    ("I", "Site accessibility primarily affects:",
     ["Photosynthesis", "Transport cost and marketing", "Soil fertility", "Pest incidence"], 1,
     "Can you get inputs in and harvest out?"),
    ("I", "History of the land is important to know:",
     ["Previous pest/disease outbreaks", "Who owned it", "The view", "The tax"], 1,
     "Soil-borne diseases might persist."),
    ("I", "The ideal pH range for most agricultural crops is:",
     ["3.0 - 4.0", "5.5 - 6.5", "8.0 - 9.0", "1.0 - 2.0"], 1,
     "Slightly acidic is best for nutrient availability."),
    ("I", "Proximity to a water source is most critical for:",
     ["Vegetable production", "Cactus", "Forestry", "Pasture"], 1,
     "Veg crops have high water demand."),
    ("I", "In site selection, 'Solar Radiation' availability is influenced by:",
     ["Soil type", "Aspect (direction of slope) and Shading", "Wind", "Rain"], 1,
     "South/East facing slopes get more light."),
    ("I", "Soil depth is critical for:",
     ["Root anchorage and volume", "Leaf color", "Seed size", "Flower color"], 1,
     "Deep roots need deep soil."),
    ("I", "Wind exposure should be considered to:",
     ["Increase transpiration", "Avoid physical damage to crops", "Dry the soil", "Cool the plants"], 1,
     "Typhoon belts require windbreaks."),
    ("I", "Which crop prefers acidic soils (pH 4.5-5.5)?",
     ["Alfalfa", "Pineapple", "Asparagus", "Barley"], 1,
     "Pineapple tolerates acidity. Alfalfa/Asparagus like neutral/alkaline."),
    ("I", "Market proximity is a key factor for:",
     ["Grains (Rice)", "Perishable crops (Vegetables/Cut flowers)", "Timber", "Copra"], 1,
     "Perishables spoil quickly."),
    ("I", "Land capability classification determines:",
     ["The price of land", "Suitability of land for specific uses (crops vs forest)", "The owner", "The tax"], 1,
     "Classifies land based on limitations (slope, soil).")
]

# Fill remaining to reach 150 (Adding 12 more variations)
extras = [
    ("B", "Botanically, a tomato fruit is a:", ["Drupe", "Berry", "Pome", "Nut"], 1, "Tomatoes are fleshy berries."),
    ("B", "Peanut (*Arachis hypogaea*) is unique because:", ["It flowers underground", "It buries its fruit (peg) underground", "It has no roots", "It is a tree"], 1, "Geocarpy: flowers above, fruits below."),
    ("E", "Which nutrient deficiency causes 'Interveinal Chlorosis' in young leaves?", ["Nitrogen", "Iron", "Potassium", "Phosphorus"], 1, "Iron is immobile; veins remain green, tissue turns yellow."),
    ("H", "A 'Herbicides' is used to control:", ["Insects", "Weeds", "Fungi", "Nematodes"], 1, "Herbicides kill plants (weeds)."),
    ("F", "Detasseling is a practice in Hybrid Corn production to:", ["Harvest corn", "Ensure cross-pollination (female rows)", "Kill pests", "Fertilize"], 1, "Removing male parts (tassels) from female rows."),
    ("D", "Which crop is a 'Short-day' plant?", ["Rice", "Cucumber", "Tomato", "Corn"], 0, "Traditional rice varieties flower when days shorten."),
    ("G", "Which is a 'Green Manure' crop?", ["Sesbania / Kudzu", "Rice", "Corn", "Coconut"], 0, "Legumes plowed under."),
    ("C", "Kranz Anatomy is characteristic of:", ["C3 Plants", "C4 Plants", "CAM Plants", "All plants"], 1, "Specialized leaf anatomy in C4 (Corn/Sugar)."),
    ("A", "The practice of growing only one crop season after season is:", ["Monocropping", "Intercropping", "Relay cropping", "Mixed cropping"], 0, "Monocropping."),
    ("E", "Typhoon signals are issued by:", ["DA", "PAGASA", "DENR", "DOH"], 1, "PAGASA manages weather."),
    ("F", "A 'Synthetic Variety' is developed from:", ["One parent", "Polycross of several inbred lines", "Cloning", "Mutation"], 1, "Open-pollinated population from selected parents."),
    ("B", "Abaca belongs to the family:", ["Poaceae", "Musaceae", "Arecaceae", "Liliaceae"], 1, "Musaceae (Banana family)."),
    ("H", "Stratification is a seed treatment using:", ["Heat", "Cold", "Acid", "Scarification"], 1, "Cold moist treatment to break dormancy."),
    ("C", "The edible part of the potato is a:", ["Root", "Tuber (Stem)", "Fruit", "Leaf"], 1, "Tuber is a swollen underground stem."),
    ("I", "Clay soils have:", ["High drainage", "High water holding capacity", "Low nutrient retention", "Large pores"], 1, "Clay holds water well but drains poorly.")
]

questions_data.extend(extras)

# --- PDF GENERATION ---
def create_pdf(filename):
    doc = SimpleDocTemplate(filename, pagesize=LETTER)
    elements = []
    
    # Styles
    styles = getSampleStyleSheet()
    title_style = styles["Title"]
    h1_style = styles["Heading1"]
    normal_style = styles["Normal"]
    
    # Custom Styles
    q_style = ParagraphStyle(name='Question', parent=styles['Normal'], fontName='Helvetica-Bold', fontSize=11, spaceAfter=6)
    c_style = ParagraphStyle(name='Choice', parent=styles['Normal'], leftIndent=20, spaceAfter=2)
    r_style = ParagraphStyle(name='Rationale', parent=styles['Normal'], fontName='Helvetica-Oblique', fontSize=10, textColor=colors.darkblue, leftIndent=20, spaceBefore=4, spaceAfter=12)

    # Title Page
    elements.append(Paragraph("COMPREHENSIVE CROP SCIENCE REVIEWER", title_style))
    elements.append(Paragraph("(Based on Licensure Examination for Agriculturists TOS)", styles["Heading2"]))
    elements.append(Spacer(1, 0.5*inch))
    elements.append(Paragraph("<b>Instructions:</b> This reviewer contains 150 items covering all major areas of Crop Science. Each item is followed by a rationale explaining the correct answer.", normal_style))
    elements.append(PageBreak())

    # Question Loop
    current_topic = ""
    q_num = 1
    
    topic_map = {
        "A": "A. NATURE AND IMPORTANCE OF AGRICULTURE",
        "B": "B. CLASSIFICATION OF CROPS",
        "C": "C. CROP ANATOMY AND MORPHOLOGY",
        "D": "D. PLANT GROWTH AND DEVELOPMENT",
        "E": "E. FACTORS AFFECTING CROP PRODUCTION",
        "F": "F. CROP IMPROVEMENT AND SEED SELECTION",
        "G": "G. SUSTAINABLE CROP PRODUCTION",
        "H": "H. CROP PRODUCTION PRACTICES",
        "I": "I. SITE SELECTION AND CHARACTERIZATION"
    }

    for topic_code, q_text, choices, correct_idx, rationale in questions_data:
        # Check for topic change
        if topic_code != current_topic:
            if current_topic != "": elements.append(PageBreak())
            current_topic = topic_code
            elements.append(Paragraph(topic_map.get(topic_code, topic_code), h1_style))
            elements.append(Spacer(1, 12))
        
        # Question
        elements.append(Paragraph(f"{q_num}. {q_text}", q_style))
        
        # Choices
        letters = ['A', 'B', 'C', 'D']
        for i, choice in enumerate(choices):
            elements.append(Paragraph(f"{letters[i]}. {choice}", c_style))
            
        # Rationale
        correct_letter = letters[correct_idx]
        r_text = f"<b>ANSWER: {correct_letter}</b><br/><i>Rationale: {rationale}</i>"
        elements.append(Paragraph(r_text, r_style))
        
        q_num += 1

    doc.build(elements)

create_pdf("Crop_Science_Reviewer_150_Items.pdf")